### ISSUE TITLE
Connection to the database: tests failing because archiving is not yet done.

### ISSUE THREAD

**Issue by JulienPeloton** [astrolabsoftware/fink-broker#153]
**Describe the issue**
When testing `connect_to_raw_database`, the test fails with:

```
File "/home/travis/build/astrolabsoftware/fink-broker/python/fink_broker/sparkUtils.py", line 251, in __main__.connect_to_raw_database
Failed example:
    dfstream_tmp = connect_to_raw_database(
      "archive/alerts_store", "archive/alerts_store/*", True)
Exception raised:
    Traceback (most recent call last):
      File "/home/travis/build/astrolabsoftware/fink-broker/spark-2.4.0-bin-hadoop2.7/python/pyspark/sql/utils.py", line 63, in deco
        return f(*a, **kw)
      File "/home/travis/build/astrolabsoftware/fink-broker/spark-2.4.0-bin-hadoop2.7/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
        format(target_id, ".", name), value)
    py4j.protocol.Py4JJavaError: An error occurred while calling o138.load.
    : org.apache.spark.sql.AnalysisException: Path does not exist: file:/home/travis/build/astrolabsoftware/fink-broker/archive/alerts_store;
```

this happens because the raw database has not yet been created (we run first the unit tests and then the integration ones).

**To Reproduce**
_Steps to reproduce the behaviour:_
1. Trigger a job in the CI (bug appeared with https://github.com/astrolabsoftware/fink-broker/commit/f4c48271a86858fc562bb96d289afceb936fb315)
2. Observe the failure.

**Comment by JulienPeloton** [comment]
Fixed in #154
