### ISSUE TITLE
Pipelines fail for last versions of Pandas (> 1.2) and pyarrow 0.14

### ISSUE THREAD

**Issue by JulienPeloton** [astrolabsoftware/fink-broker#413]
**Describe the issue**

The CI pipelines are failing when testing against Python 3.7, with error (full log [here](https://travis-ci.org/github/astrolabsoftware/fink-broker/jobs/757053972)):

```
org.apache.spark.sql.execution.streaming.StreamExecution.org$apache$spark$sql$execution$streaming$StreamExecution$$runStream(StreamExecution.scala:281)
	at org.apache.spark.sql.execution.streaming.StreamExecution$$anon$1.run(StreamExecution.scala:193)
Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 1 times, most recent failure: Lost task 0.0 in stage 0.0 (TID 0, localhost, executor driver): org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/home/travis/build/astrolabsoftware/fink-broker/spark-2.4.4-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/worker.py", line 377, in main
    process()
  File "/home/travis/build/astrolabsoftware/fink-broker/spark-2.4.4-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/worker.py", line 372, in process
    serializer.dump_stream(func(split_index, iterator), outfile)
  File "/home/travis/build/astrolabsoftware/fink-broker/spark-2.4.4-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/serializers.py", line 287, in dump_stream
    batch = _create_batch(series, self._timezone)
  File "/home/travis/build/astrolabsoftware/fink-broker/spark-2.4.4-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/serializers.py", line 256, in _create_batch
    arrs = [create_array(s, t) for s, t in series]
  File "/home/travis/build/astrolabsoftware/fink-broker/spark-2.4.4-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/serializers.py", line 256, in <listcomp>
    arrs = [create_array(s, t) for s, t in series]
  File "/home/travis/build/astrolabsoftware/fink-broker/spark-2.4.4-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/serializers.py", line 240, in create_array
    return pa.Array.from_pandas(s, mask=mask).cast(t, safe=False)
  File "pyarrow/array.pxi", line 593, in pyarrow.lib.Array.from_pandas
  File "pyarrow/array.pxi", line 191, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 78, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 95, in pyarrow.lib.check_status
pyarrow.lib.ArrowTypeError: Did not pass numpy.dtype object
```

Interestingly enough, the pipelines in Python 3.6 are all passing. By looking at the installed dependencies in the two pipelines, I notice the Pandas version is different:

| Python version | Pandas version | Pipeline status |
|----|----|-----|
| 3.6.7 | 1.1.5 | Pass |
| 3.7.1 | 1.2.1 | Fail |

Looking at the [log](https://pandas.pydata.org/docs/whatsnew/v1.2.0.html#increased-minimum-version-for-python) release of Pandas 1.2, it says minimum version is Python 3.7.1. More interesting, is that pyarrow version compatibility has been increased to 0.15 (see [here](https://pandas.pydata.org/docs/whatsnew/v1.2.0.html#increased-minimum-versions-for-dependencies)). We are currently forcing pyarrow to stay at 0.14 for [this reason](https://issues.apache.org/jira/browse/SPARK-29367). 

It is maybe time to 

1. [ ] bump pyarrow version?
2. [ ] drop python 3.6 support?
3. [ ] bump spark version to 3.0?

**Comment by JulienPeloton** [comment]
Note also from [here](https://spark.apache.org/docs/latest/sql-pyspark-pandas-with-arrow.html#recommended-pandas-and-pyarrow-versions):

```
For usage with pyspark.sql, the supported versions of Pandas is 0.24.2 and PyArrow is 0.15.1. 
Higher versions may be used, however, compatibility and data correctness can not be 
guaranteed and should be verified by the user.
```

**Comment by JulienPeloton** [comment]
Solved with more recent versions of packages.
