### ISSUE TITLE
HDFS issues

### ISSUE THREAD

**Issue by JulienPeloton** [astrolabsoftware/fink-broker#635]
```
22/07/28 22:35:08 WARN hdfs.LeaseRenewer: Failed to renew lease for [DFSClient_NONMAPREDUCE_252702987_27] for 30 seconds.  Will retry shortly ...
 org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.hdfs.server.namenode.SafeModeException): Cannot renew lease for DFSClient_NONMAPREDUCE_252702987_27.  Name node is in safe mode.
 It was turned on manually. Use "hdfs dfsadmin -safemode leave" to turn safe mode off. NamenodeHostName:vm-75222.lal.in2p3.fr
     at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.newSafemodeException(FSNamesystem.java:1407)
     at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.checkNameNodeSafeMode(FSNamesystem.java:1395)
     at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.renewLease(FSNamesystem.java:3648)
     at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.renewLease(NameNodeRpcServer.java:1087)
     at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.renewLease(ClientNamenodeProtocolServerSideTranslatorPB.java:682)
     at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
     at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:447)
     at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:989)
     at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:850)
     at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:793)
     at java.security.AccessController.doPrivileged(Native Method)
     at javax.security.auth.Subject.doAs(Subject.java:422)
     at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1840)
     at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2489)
 
     at org.apache.hadoop.ipc.Client.call(Client.java:1476)

```

**Comment by JulienPeloton** [comment]
Transient, and related to the platform.
