### ISSUE TITLE
[Fink-FAT] Data is not processed

### ISSUE THREAD

**Issue by JulienPeloton** [astrolabsoftware/fink-broker#710]
Looking at the database log for 2023-05-27:

```
Query fink broker to get sso alerts for the night between 2023-05-27 and 2023-05-28
 error when trying to get fink alerts !!!
      number of alerts get from the API call (798) is different from the real number of alerts (0)
     try again !
 error when trying to get fink alerts !!!
      number of alerts get from the API call (798) is different from the real number of alerts (0)
     try again !
 error when trying to get fink alerts !!!
      number of alerts get from the API call (798) is different from the real number of alerts (0)
     try again !
 error when trying to get fink alerts !!!
      number of alerts get from the API call (798) is different from the real number of alerts (0)
     try again !
 error when trying to get fink alerts !!!
      number of alerts get from the API call (798) is different from the real number of alerts (0)
     try again !
 Traceback (most recent call last):
   File "/opt/anaconda/bin/fink_fat", line 8, in <module>
     sys.exit(main())
   File "/opt/Anaconda3-2020.02/lib/python3.7/site-packages/bin/fink_fat_cli.py", line 1283, in main
     fink_fat_main(arguments)
   File "/opt/Anaconda3-2020.02/lib/python3.7/site-packages/bin/fink_fat_cli.py", line 171, in fink_fat_main
     last_nid = next_nid = new_alerts["nid"][0]
   File "/opt/Anaconda3-2020.02/lib/python3.7/site-packages/pandas/core/series.py", line 939, in __getitem__
     return self._values[key]
 IndexError: index 0 is out of bounds for axis 0 with size 0
```

But I ran the fink-FAT command 2 hours later:

```
fink_fat associations candidates --config $FINK_HOME/conf/fink_fat.conf --night ${YEAR}-${MONTH}-${DAY}
```

and this time:

```
Query fink broker to get sso alerts for the night between 2023-05-27 and 2023-05-28
Number of alerts retrieve from fink: 798
time taken to retrieve alerts from fink broker: 2.2662274837493896

started associations...
elapsed time to find tracklets : 0.3798820972442627
Association done
```

what could go wrong? The job that pushes SSO candidates data is done before, but only 2min before (WRONG! See last comment about `stats`). Is it enough to make the data available? I would be surprised if one needs to wait more than 2min to get data once it has been pushed...

**Comment by JulienPeloton** [comment]
To do:
- [ ] Put a sleep (2 min) before, and see if data is processed.
- [ ] If not, separate the fink-FAT processing from the rest, and schedule it 2 hours later.

**Comment by JulienPeloton** [comment]
Indeed last update was:

```
In [8]: Time(np.max(pdf['d:jd']), format='jd').iso
Out[8]: '2023-01-24 03:44:08.998'
```

**Comment by JulienPeloton** [comment]
For information, I backed up parquet data from `2019-11-02` to `2023-03-01` (last run -- even though candidates stopped in January). I removed files, and re-run fink-FAT offline from this point onward, and push data to HBase. Now:

```
In [1]: import io
   ...: import requests
   ...: import pandas as pd
   ...: 
   ...: r = requests.post(
   ...:   'https://fink-portal.org/api/v1/ssocand',
   ...:   json={
   ...:     'kind': 'lightcurves'
   ...:   }
   ...: )
   ...: 
   ...: # Format output in a DataFrame
   ...: pdf = pd.read_json(io.BytesIO(r.content))

In [2]: import numpy as np

In [3]: from astropy.time import Time

In [4]: Time(np.max(pdf['d:jd']), format='jd').iso
Out[4]: '2023-05-27 10:14:36.997'
```

Note on aside (open issue in Fink-FAT):

```
# performance using offline mode
fink_fat offline candidates cluster 2023-05-28 2023-05-28 --config $CONFIG --verbose
time taken to get orbit: 26.48713779449463

# performance using local model
fink_fat associations candidates --config $FINK_HOME/conf/fink_fat.conf --night 2023-05-27
fink_fat solve_orbit candidates local --config $FINK_HOME/conf/fink_fat.conf --verbose
time taken to get orbit: 2.864030122756958
```

**Comment by JulienPeloton** [comment]
oh now I understand -- the `real number of alerts (0)` is given by the `stats` service, which is updated afterwards...
