### ISSUE TITLE
science2grb_offline: missing deps (py4j)

### ISSUE THREAD

**Issue by JulienPeloton** [astrolabsoftware/fink-broker#712]
```
Subject: Cron <julien.peloton@vm-75222> /home/julien.peloton/Fink_GRB/scheduler/science2grb_offline.sh

Traceback (most recent call last):
  File "/opt/anaconda/bin/fink_grb", line 8, in <module>
    sys.exit(main())
  File "/opt/Anaconda3-2020.02/lib/python3.7/site-packages/fink_grb/fink_grb_cli.py", line 56, in main
    from fink_grb.offline.spark_offline import launch_offline_mode
  File "/opt/Anaconda3-2020.02/lib/python3.7/site-packages/fink_grb/offline/spark_offline.py", line 4, in <module>
    from fink_utils.science.utils import ang2pix
  File "/opt/Anaconda3-2020.02/lib/python3.7/site-packages/fink_utils/science/utils.py", line 15, in <module>
    from pyspark.sql.functions import pandas_udf, PandasUDFType
  File "/opt/spark-3/python/pyspark/__init__.py", line 53, in <module>
    from pyspark.rdd import RDD, RDDBarrier
  File "/opt/spark-3/python/pyspark/rdd.py", line 34, in <module>
    from pyspark.java_gateway import local_connect_and_auth
  File "/opt/spark-3/python/pyspark/java_gateway.py", line 29, in <module>
    from py4j.java_gateway import java_import, JavaGateway, JavaObject, GatewayParameters
ModuleNotFoundError: No module named 'py4j'

```

mama mia. Recent Spark upgrade?

**Comment by JulienPeloton** [comment]
Yes, it was a problem of the recent Spark installation.
