### ISSUE TITLE
KeyError: 'type'

### ISSUE THREAD

**Issue by JulienPeloton** [astrolabsoftware/fink-broker#821]
Running the `early_kn_candidates` filter:

```
org.apache.spark.SparkException: Job aborted due to stage failure: Task 2 in stage 5880.0 failed 4 times, most recent failure: Lost task 2.3 in stage 5880.0  (TID 28000) (vm-75102.lal.in2p3.fr executor 0): org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/opt/anaconda/lib/python3.9/site-packages/fink_filters/filter_early_kn_candidates/filter.py", line 279, in early_kn_candidates
    out = perform_classification(
  File "/opt/anaconda/lib/python3.9/site-packages/fink_filters/filter_early_kn_candidates/filter.py", line 139, in perform_classification
    type_close_objects = table['type']
  File "/opt/anaconda/lib/python3.9/site-packages/astropy/table/table.py", line 1872, in __getitem__
    return self.columns[item]
  File "/opt/anaconda/lib/python3.9/site-packages/astropy/table/table.py", line 246, in __getitem__
    return OrderedDict.__getitem__(self, item)
KeyError: 'type'

```

API change for astropy? The dependencies have not been updated recently though...

**Comment by JulienPeloton** [comment]
Never happened again
