### ISSUE TITLE
Hostless detection fails with KeyError

### ISSUE THREAD

**Issue by JulienPeloton** [astrolabsoftware/fink-broker#872]
It starts on 08/25 -- not sure what is happening there:

```
Traceback (most recent call last):
  File "/home/julien.peloton/fink-broker/bin/hostless_detection.py", line 153, in <module>
    main()
  File "/home/julien.peloton/fink-broker/bin/hostless_detection.py", line 126, in main
    curve_png = get_curve(
  File "/opt/anaconda/lib/python3.9/site-packages/fink_utils/tg_bot/utils.py", line 336, in get_curve
    pdf[maskUpper & maskFilt]["i:diffmaglim"],
  File "/opt/anaconda/lib/python3.9/site-packages/pandas/core/frame.py", line 3458, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/opt/anaconda/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'i:diffmaglim'

```

**Comment by JulienPeloton** [comment]
Note that other bots using `diffmaglim` do not fail.
